// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ1kONdeHt42rQiJXPNv5YBYudUlDks-E',
    appId: '1:976122112028:web:4d75985e08340617bb97d9',
    messagingSenderId: '976122112028',
    projectId: 'wasteless-96f3a',
    authDomain: 'wasteless-96f3a.firebaseapp.com',
    storageBucket: 'wasteless-96f3a.firebasestorage.app',
    measurementId: 'G-NKMC9T02WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxCRBcJi8wXwJZpD1UqyN0_ooJV74023s',
    appId: '1:976122112028:android:705fd7319da31ee3bb97d9',
    messagingSenderId: '976122112028',
    projectId: 'wasteless-96f3a',
    storageBucket: 'wasteless-96f3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIhnYnjoY8DXarEcORy4XAyVazdAeXu-k',
    appId: '1:976122112028:ios:60f7c4abe2348da3bb97d9',
    messagingSenderId: '976122112028',
    projectId: 'wasteless-96f3a',
    storageBucket: 'wasteless-96f3a.firebasestorage.app',
    iosClientId: '976122112028-covp03aq2mclft2nc4tkdb4fkqditda7.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibelab',
  );
}
